[build]
publish = "public"
command = "hugo --minify"

[context.production.environment]
HUGO_VERSION = "0.61.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview.environment]
HUGO_VERSION = "0.61.0"

[[redirects]]
  from = ""
  to = ""
  status = 301
  force = true

[[redirects]]
  from = ""
  to = ""
  status = 301
  force = true